header: {stamp: {sec: 0, nanosec: 0}, frame_id: ""}
joint_names: ['shoulder_pan_joint', 'shoulder_lift_joint', 'elbow_joint', 'wrist_1_joint', 'wrist_2_joint', 'wrist_3_joint']
points:
  - positions: [0.0, -1.2473977247821253, 1.7533230781555176, -2.0766728560077112, -1.570808235798971, -2.0030015150653284]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    time_from_start:
      sec: 0
      nanosec: 0
  - positions: [0.5798694491386414, -0.9893663565265101, 1.3605260848999023, -1.9419696966754358, -1.5707600752459925, -1.4256966749774378]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    time_from_start:
      sec: 8
      nanosec: 0
  - positions: [0.7977606654167175, -1.2910640875445765, 1.8131895065307617, -2.092898193989889, -1.5707600752459925, -1.2077210585223597]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    time_from_start:
      sec: 12
      nanosec: 0
  - positions: [-0.6771205107318323, -1.882510010396139, 2.393008232116699, -2.0813310782061976, -1.570796314870016, -2.6826728026019495]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    time_from_start:
      sec: 20
      nanosec: 0
  - positions: [0.0, -1.2473977247821253, 1.7533230781555176, -2.0766728560077112, -1.570808235798971, -2.0030015150653284]
    velocities: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    accelerations: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    effort: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    time_from_start:
      sec: 24
      nanosec: 0
